/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactItems?: Array<{
    title?: string;
    subtitle?: string;
    icon?: string;
    _key: string;
  }>;
  quickLinks?: Array<{
    title?: string;
    href?: string;
    _key: string;
  }>;
  categories?: Array<{
    title?: string;
    href?: string;
    _key: string;
  }>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tagline?: string;
  footerBottomText?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  newsletterText?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HeaderSettings = {
  _id: string;
  _type: "headerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navigationLinks?: Array<{
    title?: string;
    href?: string;
    _key: string;
  }>;
  callToAction?: {
    label?: string;
    href?: string;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  catalogueMode?: boolean;
};

export type TextContentBlock = {
  _type: "textContentBlock";
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ProductGridBlock = {
  _type: "productGridBlock";
  title?: string;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
};

export type HeroBlock = {
  _type: "heroBlock";
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaLink?: string;
  ctaText?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & ProductGridBlock)
    | ({
        _key: string;
      } & TextContentBlock)
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  isFullBleedGraphic?: boolean;
  headline?: string;
  bannerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  targetUrl?: string;
  buttonText?: string;
  backgroundColor?: string;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogcategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogcategory";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<
    {
      _key: string;
    } & BlogcategoryReference
  >;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  default?: boolean;
  createdAt?: string;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "pending"
    | "processing"
    | "paid"
    | "shipped"
    | "out_for_delivery"
    | "delivered"
    | "cancelled";
  orderDate?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type ProductVariantReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productVariant";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  variant?: ProductVariantReference;
  status?: "new" | "hot" | "sale";
  isFeatured?: boolean;
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | FooterSettings
  | SanityImageCrop
  | SanityImageHotspot
  | HeaderSettings
  | SiteSettings
  | TextContentBlock
  | ProductReference
  | ProductGridBlock
  | HeroBlock
  | Page
  | Slug
  | Banner
  | Blogcategory
  | AuthorReference
  | BlogcategoryReference
  | Blog
  | Author
  | Address
  | Order
  | Category
  | CategoryReference
  | BrandReference
  | ProductVariantReference
  | Product
  | ProductVariant
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/query.ts
// Variable: BRANDS_QUERY
// Query: *[_type=='brand'] | order(title asc)
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: sanity/queries/query.ts
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(title asc){      ...,      blogcategories[]->{      title    }    }
export type LATEST_BLOG_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest: true;
  body?: BlockContent;
}>;

// Source: sanity/queries/query.ts
// Variable: DEAL_PRODUCTS
// Query: *[_type == 'product' && status == 'hot'] | order(name asc){    ...,    "categories": categories[]->title,    brand->{title},    variant->{title}  }
export type DEAL_PRODUCTS_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand: {
    title: string | null;
  } | null;
  variant: {
    title: string | null;
  } | null;
  status: "hot";
  isFeatured?: boolean;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    ...,    stock,    price,    discount,    brand->{      _id,      title,      description    },    variant->{      _id,      title    },    categories[]->{      _id,      title    }  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price: number | null;
  discount: number | null;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  stock: number | null;
  brand: {
    _id: string;
    title: string | null;
    description: string | null;
  } | null;
  variant: {
    _id: string;
    title: string | null;
  } | null;
  status?: "hot" | "new" | "sale";
  isFeatured?: boolean;
} | null;

// Source: sanity/queries/query.ts
// Variable: BRAND_QUERY
// Query: *[_type == "product" && slug.current == $slug]{  "brandName": brand->title  }
export type BRAND_QUERY_RESULT = Array<{
  brandName: string | null;
}>;

// Source: sanity/queries/query.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    catalogueMode  }
export type SITE_SETTINGS_QUERY_RESULT = {
  catalogueMode: boolean | null;
} | null;

// Source: sanity/queries/query.ts
// Variable: HEADER_SETTINGS_QUERY
// Query: *[_type == "headerSettings"][0]{    logo,    navigationLinks[]{      title,      href    },    callToAction{      text,      url    }  }
export type HEADER_SETTINGS_QUERY_RESULT = {
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  navigationLinks: Array<{
    title: string | null;
    href: string | null;
  }> | null;
  callToAction: {
    text: null;
    url: null;
  } | null;
} | null;

// Source: sanity/queries/query.ts
// Variable: FOOTER_SETTINGS_QUERY
// Query: *[_type == "footerSettings"][0]{    contactItems[]{      title,      subtitle,      icon    },    quickLinks[]{      title,      href    },    categories[]{      title,      href    },    socialLinks[]{      platform,      url    },    newsletterText  }
export type FOOTER_SETTINGS_QUERY_RESULT = {
  contactItems: Array<{
    title: string | null;
    subtitle: string | null;
    icon: string | null;
  }> | null;
  quickLinks: Array<{
    title: string | null;
    href: string | null;
  }> | null;
  categories: Array<{
    title: string | null;
    href: string | null;
  }> | null;
  socialLinks: Array<{
    platform: string | null;
    url: string | null;
  }> | null;
  newsletterText: string | null;
} | null;

// Source: sanity/queries/query.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){    ...,    products[]{      ...,      product->    }  }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      description?: string;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      brand?: BrandReference;
      variant?: ProductVariantReference;
      status?: "hot" | "new" | "sale";
      isFeatured?: boolean;
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "cancelled"
    | "delivered"
    | "out_for_delivery"
    | "paid"
    | "pending"
    | "processing"
    | "shipped";
  orderDate?: string;
}>;

// Source: sanity/queries/query.ts
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{    ...,      blogcategories[]->{      title    }  }
export type GET_ALL_BLOG_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;

// Source: sanity/queries/query.ts
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{    ...,     author->{      name,      image,    },    blogcategories[]->{      title,      "slug": slug.current,    },  }
export type SINGLE_BLOG_QUERY_RESULT = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
} | null;

// Source: sanity/queries/query.ts
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{     blogcategories[]->{       ...     }  }
export type BLOG_CATEGORIES_RESULT = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: sanity/queries/query.ts
// Variable: OTHERS_BLOG_QUERY
// Query: *[    _type == "blog"    && defined(slug.current)    && slug.current != $slug  ]|order(publishedAt desc)[0...$quantity]{    ...,    publishedAt,    title,    mainImage,    slug,    author->{      name,      image,    },    categories[]->{      title,      "slug": slug.current,    }  }
export type OTHERS_BLOG_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  blogcategories?: Array<
    {
      _key: string;
    } & BlogcategoryReference
  >;
  publishedAt: string | null;
  isLatest?: boolean;
  body?: BlockContent;
  categories: null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type=='brand'] | order(title asc)": BRANDS_QUERY_RESULT;
    " *[_type == 'blog' && isLatest == true]|order(title asc){\n      ...,\n      blogcategories[]->{\n      title\n    }\n    }": LATEST_BLOG_QUERY_RESULT;
    "*[_type == 'product' && status == 'hot'] | order(name asc){\n    ...,\n    \"categories\": categories[]->title,\n    brand->{title},\n    variant->{title}\n  }": DEAL_PRODUCTS_RESULT;
    '*[_type == "product" && slug.current == $slug][0]{\n    ...,\n    stock,\n    price,\n    discount,\n    brand->{\n      _id,\n      title,\n      description\n    },\n    variant->{\n      _id,\n      title\n    },\n    categories[]->{\n      _id,\n      title\n    }\n  }': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug]{\n  "brandName": brand->title\n  }': BRAND_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n    catalogueMode\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "headerSettings"][0]{\n    logo,\n    navigationLinks[]{\n      title,\n      href\n    },\n    callToAction{\n      text,\n      url\n    }\n  }': HEADER_SETTINGS_QUERY_RESULT;
    '*[_type == "footerSettings"][0]{\n    contactItems[]{\n      title,\n      subtitle,\n      icon\n    },\n    quickLinks[]{\n      title,\n      href\n    },\n    categories[]{\n      title,\n      href\n    },\n    socialLinks[]{\n      platform,\n      url\n    },\n    newsletterText\n  }': FOOTER_SETTINGS_QUERY_RESULT;
    "\n  *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){\n    ...,\n    products[]{\n      ...,\n      product->\n    }\n  }\n": MY_ORDERS_QUERY_RESULT;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n    ...,  \n    blogcategories[]->{\n      title\n    }\n  }": GET_ALL_BLOG_RESULT;
    '\n  *[_type == "blog" && slug.current == $slug][0]{\n    ..., \n    author->{\n      name,\n      image,\n    },\n    blogcategories[]->{\n      title,\n      "slug": slug.current,\n    },\n  }\n': SINGLE_BLOG_QUERY_RESULT;
    '*[_type == "blog"]{\n     blogcategories[]->{\n       ...\n     }\n  }': BLOG_CATEGORIES_RESULT;
    '\n  *[\n    _type == "blog"\n    && defined(slug.current)\n    && slug.current != $slug\n  ]|order(publishedAt desc)[0...$quantity]{\n    ...,\n    publishedAt,\n    title,\n    mainImage,\n    slug,\n    author->{\n      name,\n      image,\n    },\n    categories[]->{\n      title,\n      "slug": slug.current,\n    }\n  }\n': OTHERS_BLOG_QUERY_RESULT;
  }
}
